[theme]
primaryColor="#F63366"  # The main color for buttons and links
backgroundColor="#FFFFFF"  # The background color of the main content area
secondaryBackgroundColor="#F0F2F6"  # The background for sidebars and other containers
textColor="#262730"  # The font color
font="sans serif"  # The font family (options: "sans serif", "serif", or "monospace")
